import { User } from "../../models/user";

export default {
  "login": "ArtyomZakharenko",
  "id": 61537821,
  "node_id": "MDQ6VXNlcjYxNTM3ODIx",
  "avatar_url": "https://avatars.githubusercontent.com/u/61537821?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/ArtyomZakharenko",
  "html_url": "https://github.com/ArtyomZakharenko",
  "followers_url": "https://api.github.com/users/ArtyomZakharenko/followers",
  "following_url": "https://api.github.com/users/ArtyomZakharenko/following{/other_user}",
  "gists_url": "https://api.github.com/users/ArtyomZakharenko/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/ArtyomZakharenko/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/ArtyomZakharenko/subscriptions",
  "organizations_url": "https://api.github.com/users/ArtyomZakharenko/orgs",
  "repos_url": "https://api.github.com/users/ArtyomZakharenko/repos",
  "events_url": "https://api.github.com/users/ArtyomZakharenko/events{/privacy}",
  "received_events_url": "https://api.github.com/users/ArtyomZakharenko/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Artsem Zakharanka",
  "company": null,
  "blog": "",
  "location": "Belarus",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 53,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2020-02-27T08:15:50Z",
  "updated_at": "2022-09-01T09:34:17Z"
} as User;
